import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SessionLayout from "./SessionLayout"; // นำเข้า SessionLayout
import type { ReactNode } from "react";

// Export metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ใช้ SessionLayout
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="th">
      <body>
        <SessionLayout> {/* ใช้ SessionLayout แทน SessionProvider */}
          {children}
        </SessionLayout>
      </body>
    </html>
  );
}
